apiVersion: apps/v1
kind: Deployment
metadata:
  name: medusa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: medusa
  template:
    metadata:
      labels:
        app: medusa
    spec:
      containers:
        - name: medusa
          image: jaspreet237/medusajsv2:ver1
          ports:
            - containerPort: 9000
          env:
            - name: DATABASE_URL
              value: postgres://medusa:medusa@postgres/medusa?ssl_mode=disable
            - name: REDIS_URL
              value: redis://medusa-redis:6379
          command: ["/bin/bash", "-c"]
          args:
            - |
              npx medusa db:setup --no-interactive && 
              npx medusa start
---
apiVersion: v1
kind: Service
metadata:
  name: medusa-service
spec:
  selector:
    app: medusa
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
  type: LoadBalancer
