# ------------------ MEDUSA DEPLOYMENT ------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: medusa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: medusa
  template:
    metadata:
      labels:
        app: medusa
    spec:
      containers:
        - name: medusa
          image: jaspreet237/medusajsv2:ver1
          ports:
            - containerPort: 9000
          env:
            - name: DATABASE_URL
              value: postgres://medusa:medusa@postgres/medusa?ssl_mode=disable
            - name: REDIS_URL
              value: redis://medusa-redis:6379
          command: ["/bin/bash", "-c"]
          args:
            - |
              npx medusa db:setup --no-interactive && 
              npx medusa start
      initContainers:
        - name: wait-for-postgres
          image: postgres:15
          command: ['sh', '-c', 'until pg_isready -h postgres -p 5432; do echo waiting for postgres; sleep 2; done']
---
apiVersion: v1
kind: Service
metadata:
  name: medusa-service
spec:
  selector:
    app: medusa
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
  type: LoadBalancer

# ------------------ POSTGRES DEPLOYMENT ------------------
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: medusa
            - name: POSTGRES_PASSWORD
              value: medusa
            - name: POSTGRES_DB
              value: medusa

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
